### ISSUE TITLE
interpolate_na raises TypeError when using `rioxarray.open_rasterio` instead of `xarray.open_rasterio`

### ISSUE THREAD

**Issue by vedal** [corteva/rioxarray#250]
#### Code Sample
The following causes a crash:

```python
import xarray
import rioxarray

file_url = 'https://neo.sci.gsfc.nasa.gov/archive/geotiff.float/MY1DMW_CHLORA/MY1DMW_CHLORA_2020-03-21.FLOAT.TIFF'
ds = rioxarray.open_rasterio(file_url)
ds = ds.rio.write_crs("EPSG:4326")
ds = ds.sel(
    y=slice(55, 30), x=slice(165, 180)
)
ds = ds.rio.interpolate_na(method="linear")
```
while replacing `rioxarray.open_rasterio` with `xarray.open_rasterio` works fine.

#### Problem description

The problem is a crash with the error:
 `TypeError: float() argument must be a string or a number, not 'NoneType'`:
This also happens for other TIFFs. 

#### Environment Information

```
rioxarray (0.3.0) deps:
  rasterio: 1.1.8
    xarray: 0.16.2
      GDAL: 2.4.4

Other python deps:
     scipy: 1.5.4
    pyproj: 3.0.0.post1

System:
    python: 3.8.3 (default, Nov  5 2020, 11:18:23)  [Clang 9.1.0 (clang-902.0.39.1)]
executable: /Users/user/.pyenv/versions/3.8.3/envs/myenv/bin/python3.8
   machine: macOS-10.13.6-x86_64-i386-64bit
```

#### Installation method
pypi
