### ISSUE TITLE
TypeError: data type 'complex_int16' not understood

### ISSUE THREAD

**Issue by scottyhq** [corteva/rioxarray#352]
There were some changes recently in rasterio (>=1.2.4) to allow reading and writing CInt16 data (common in SAR): (https://github.com/mapbox/rasterio/issues/2182 and https://github.com/mapbox/rasterio/pull/2185) 

This dtype now maps to np.complex64 to match GDAL instead of np.complex128, but rioxarray raises an error due to the missing dtype lookup.

#### Code Sample, a copy-pastable example if possible
```python
import rasterio
import xarray as xr
import rioxarray

# rasterio >= 1.2.4
with rasterio.open('s3://my-cog-server/s1b-iw1-slc-vv-20210401-crop.tif') as src:
    print(src.profile)  # 'dtype': 'complex_int16'
    print(src.read().dtype) #complex64
    
# TypeError: data type 'complex_int16' not understood
da = rioxarray.open_rasterio('s3://my-cog-server/s1b-iw1-slc-vv-20210401-crop.tif') #TypeError: data type 'complex_int16' not understood
#ds = xr.open_dataset('s3://my-cog-server/s1b-iw1-slc-vv-20210401-crop.tif', engine='rasterio') #same goes for this
```

#### Environment Information
```
rioxarray (0.4.2) deps:
  rasterio: 1.2.4
    xarray: 0.18.2
      GDAL: 3.2.1

Other python deps:
     scipy: 1.6.3
    pyproj: 3.0.1

System:
    python: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:15)  [Clang 11.1.0 ]
executable: /Users/scott/miniconda3/envs/burstdb/bin/python
   machine: macOS-11.3-x86_64-i386-64bit
```

#### Full traceback
<details>
<summary>Click to expand</summary>
<p>

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-bdc423fb0f5c> in <module>
      9 
     10 # TypeError: data type 'complex_int16' not understood
---> 11 da = rioxarray.open_rasterio('s3://my-cog-server/s1b-iw1-slc-vv-20210401-crop.tif') #TypeError: data type 'complex_int16' not understood
     12 #ds = xr.open_dataset('s3://my-cog-server/s1b-iw1-slc-vv-20210401-crop.tif', engine='rasterio') #same goes for this

~/miniconda3/envs/burstdb/lib/python3.9/site-packages/rioxarray/_io.py in open_rasterio(filename, parse_coordinates, chunks, cache, lock, masked, mask_and_scale, variable, group, default_name, decode_times, decode_timedelta, **open_kwargs)
    888     da_name = attrs.pop("NETCDF_VARNAME", default_name)
    889     data = indexing.LazilyOuterIndexedArray(
--> 890         RasterioArrayWrapper(
    891             manager,
    892             lock,

~/miniconda3/envs/burstdb/lib/python3.9/site-packages/rioxarray/_io.py in __init__(self, manager, lock, name, vrt_params, masked, mask_and_scale, unsigned)
    175             raise ValueError("All bands should have the same dtype")
    176 
--> 177         dtype = np.dtype(dtypes[0])
    178         # handle unsigned case
    179         if mask_and_scale and unsigned and dtype.kind == "i":

TypeError: data type 'complex_int16' not understood
```

</p>
</details>
