### ISSUE TITLE
CRS set on Dataset does not persist for DataArrays obtained by selecting data variable 

### ISSUE THREAD

**Issue by vidurmithal** [corteva/rioxarray#356]
#### Code Sample

```python
da1 = xr.DataArray(np.arange(10*10).reshape(10, 10), [("x", np.linspace(70,80,10)), ("y", np.linspace(20,30,10))], name='var_1')
da2 = xr.DataArray(np.arange(10*10).reshape(10, 10), [("x", np.linspace(70,80,10)), ("y", np.linspace(20,30,10))], name='var_2')

ds = xr.merge([da1,da2])

ds = ds.rio.set_crs('epsg:4326')

print('Dataset CRS: {}'.format(ds.rio.crs))
print('DataArray 1 CRS: {}'.format(ds['var_1'].rio.crs))
print('DataArray 2 CRS: {}'.format(ds['var_2'].rio.crs))
```
#### Problem description

The CRS set on a `Dataset `using `.rio.set_crs()` does not persist to a `DataArray` obtained by selecting individual variables from the `Dataset`. Printing the CRS of the `Dataset` gives the previously set CRS, but printing the CRS of the `DataArray` gives `None`. 

#### Expected Output

The CRS set on a `Dataset` should also apply to `DataArrays` of individual variables. Printing `DataArray.rio.crs` should give the set CRS, `EPSG:4326` in this case.

#### Environment Information

```
rioxarray (0.1.1) deps:
  rasterio: 1.1.0
    xarray: 0.16.2
      GDAL: 3.0.2

Other python deps:
     scipy: 1.4.1
    pyproj: 2.6.0

System:
   python: 3.7.7 (default, Mar 23 2020, 22:36:06)  [GCC 7.3.0]
   machine: Linux-5.4.89+-x86_64-with-debian-bullseye-sid
```

#### Installation method
 `PyPi`
