### ISSUE TITLE
Cache flag not working?

### ISSUE THREAD

**Issue by cordmaur** [corteva/rioxarray#477]
I've wrote a simple routine just to change a nodata values for a series of rasters using rioxarray and noticed a strange behavior probably related to the way rioxarray caches data. 

When reopening the raster with rioxarray the nodata value is not changed, but when I open with rasterio (or if I reset the kernel) I can verify the value has been update correctly on the file. 

Here is a simple test:
![image](https://user-images.githubusercontent.com/19617404/154933222-aea4a700-d65d-4c50-adfa-b13630185127.png)

**Comment by snowman2** [comment]
Thanks for this. Would you mind:
- Pasting a code snippet as text instead of a screenshot?
- Providing the output from: `python -c "import rioxarray; rioxarray.show_versions()"`
- Provide the example file from before you made changes? You should be able to zip up the file and upload it here if it is small enough.

**Comment by cordmaur** [comment]
Hi @snowman2,
Here is the code and the sample file is attached.

```
import rasterio as rio
import rioxarray as xrio

src = './test.tif'
ds = xrio.open_rasterio(src, cache=False)
print(f'Nodata value: {ds.rio.nodata}')

# Changing nodata to 0
ds.rio.set_nodata(0)
print(f'Assigned nodata value: {ds.rio.nodata}')

# Overwriting file on disk
ds.rio.to_raster(src)

# Opening file in a new variable
ds2 = xrio.open_rasterio(src, cache=False)
print(f'Nodata value: {ds2.rio.nodata}')

# testing with rasterio
ds3 = rio.open(src)
print(f'Rio nodata value: {ds3.nodata}')
```
Result:
```
Nodata value: 255
Assigned nodata value: 0
Nodata value: 255
Rio nodata value: 0.0
```

<b>ENV:</b>
```
[rebellm@node527 nbs]$ python -c "import rioxarray; rioxarray.show_versions()"
rioxarray (0.7.1) deps:
  rasterio: 1.2.6
    xarray: 0.19.0
      GDAL: 3.2.1

Other python deps:
     scipy: 1.7.1
    pyproj: 3.1.0

System:
    python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)  [GCC 9.4.0]
executable: /softs/rh7/conda-envs/pangeo_stable/bin/python
   machine: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
```
[test.zip](https://github.com/corteva/rioxarray/files/8116016/test.zip)
