### ISSUE TITLE
Reading Sentinel-5P data throws "UnicodeDecodeError"

### ISSUE THREAD

**Issue by rrsc1234** [corteva/rioxarray#527]
Hi. I am trying to read sentinel-5p data using following code:

```
import rioxarray
netcdf_fname = r'D:\Projects\S5P_OFFL_L2__CH4____20220509T074431_20220509T092601_23678_02_020301_20220510T234447.nc'
rds = rioxarray.open_rasterio(netcdf_fname, group='PRODUCT')
```

After running the above code I am getting following error:
```UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 28: invalid start byte```

My installed rioxarray version is '0.9.1'.

Can someone please tell me how to reslove this issue.

Data is present at the following link:
```https://drive.google.com/file/d/1zw8kSPZPRIu_YDxixIlOByPCY19GNMbz/view?usp=sharing```

**Comment by snowman2** [comment]
Please provide the output of `rioxarray.show_versions()`.

**Comment by rrsc1234** [comment]
> Please provide the output of `rioxarray.show_versions()`.

Here is the output after running ```rioxarray.show_versions()```

```
rioxarray (0.9.1) deps:
  rasterio: 1.0.18
    xarray: 0.20.1
      GDAL: 2.3.3

Other python deps:
     scipy: 1.1.0
    pyproj: 2.6.1.post1

System:
    python: 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
executable: C:\Users\ashish\Anaconda3\pythonw.exe
   machine: Windows-10-10.0.18362-SP0
None
```
